ALTER TABLE stg_price_observations
ADD COLUMN IF NOT EXISTS price_per_unit NUMERIC,
ADD COLUMN IF NOT EXISTS unit_price_label TEXT,
ADD COLUMN IF NOT EXISTS regular_price NUMERIC,
ADD COLUMN IF NOT EXISTS discount_rate NUMERIC,
ADD COLUMN IF NOT EXISTS brand_name TEXT,
ADD COLUMN IF NOT EXISTS category_name TEXT,
ADD COLUMN IF NOT EXISTS is_suspicious BOOLEAN,
ADD COLUMN IF NOT EXISTS suspicious_reason TEXT;

ALTER TABLE fact_price_observations
ADD COLUMN IF NOT EXISTS price_per_unit NUMERIC,
ADD COLUMN IF NOT EXISTS unit_price_label TEXT,
ADD COLUMN IF NOT EXISTS regular_price NUMERIC,
ADD COLUMN IF NOT EXISTS discount_rate NUMERIC,
ADD COLUMN IF NOT EXISTS brand_name TEXT,
ADD COLUMN IF NOT EXISTS category_name TEXT;
