ALTER TABLE scrape_runs
ADD COLUMN IF NOT EXISTS category_slug TEXT,
ADD COLUMN IF NOT EXISTS triggered_by TEXT,
ADD COLUMN IF NOT EXISTS pipeline_version TEXT,
ADD COLUMN IF NOT EXISTS records_raw INTEGER,
ADD COLUMN IF NOT EXISTS records_stg INTEGER,
ADD COLUMN IF NOT EXISTS records_fact INTEGER,
ADD COLUMN IF NOT EXISTS records_suspicious INTEGER,
ADD COLUMN IF NOT EXISTS records_failed INTEGER;
