RETAILER_CONFIG = {
    "migros": {
        "source_name": "migros",
        "currency": "TRY",
        "categories": {
            "fruit_veg": "meyve-sebze-c-2",
            "dairy_breakfast": "sut-kahvaltilik-c-4",
            "beverages": "icecek-c-6",
            "bakery": "ekmek-c-455",
            "flour": "sade-un-c-289b",
            "water": "su-c-84",
            "salt": "tuz-c-436",
            "sugar_powdered": "toz-seker-c-544",
            "sugar_cube": "kup-seker-c-543",
            "cola": "kola-c-465",
            "rice_baldo": "baldo-pirincler-c-2788",
            "sunflower_oil": "aycicek-yagi-c-42d",
            "olive_oil": "zeytinyagi-c-433",
            "turkish_coffee": "turk-kahvesi-c-28c4",
            "filter_coffee": "filtre-kahve-c-11223",
            "toilet_paper": "tuvalet-kagidi-c-49c",
            "paper_towel": "kagit-havlu-c-49d",
            "dishwashing": "sivi-bulasik-deterjani-c-489",
            "dishwasher_tablets": "bulasik-makinesi-tableti-c-28eb",
            "laundry_detergent": "camasir-deterjani-c-486",
            "bleach": "camasir-suyu-c-483",
            "surface_cleaner": "sivi-yuzey-temizleyiciler-c-2912",
            "kitchen_bath_cleaner": "mutfak-ve-banyo-temizleyiciler-c-491",
        },
    },

    "a101": {
        "source_name": "a101",
        "currency": "TRY",
        "categories": {
            "fruit_veg": "meyve-sebze",
            "dairy_breakfast": "sut-urunleri-kahvaltilik",
            "bakery": "firindan",
            "flour": "temel-gida/un",
            "water": "su-icecek/su",
            "salt": "temel-gida/tuz-baharat-harc",
            "sugar": "temel-gida/seker",
            "cola": "su-icecek/gazli-icecekler",
            "rice": "temel-gida/bakliyat",
            "edible_oils": "temel-gida/sivi-yaglar",
            "coffee": "su-icecek/kahve",
            "toilet_paper": "kagit-urunleri/tuvalet-kagidi",
            "paper_towel": "kagit-urunleri/kagit-havlu",
            "dishwashing": "temizlik-urunleri/bulasik",
            "dishwasher_tablets": "temizlik-urunleri/bulasik",
            "laundry_detergent": "temizlik-urunleri/camasir",
            "bleach": "temizlik-urunleri/genel-temizlik",
            "surface_cleaner": "temizlik-urunleri/genel-temizlik",
        },
    }
}
